prSections:
- title: My Pull Requests
  filters: is:open author:@me
  layout:
    author:
      hidden: true
- title: Needs My Review
  filters: is:open review-requested:@me
- title: SRE Reviews
  filters: org:litmus -label:HOLD -label:WIP -label:Refactor draft:false is:pr is:open review:required team-review-requested:litmus/sre -repo:litmus/litmus
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs: []
repoPaths:
  litmus/*: ~/repos/github.com/litmus/*
  litmus/litmus-lambdas: ~/repos/github.com/litmus/litmus-lambdas
pager:
  diff: ""
