name: "dotfiles.checkout"
on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'

jobs:
  pre_job:
    runs-on: ubuntu-20.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master

  install:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dotfiles
        run: ./install.sh
