name: Pull Dotbot
on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Create PR
        uses: peter-evans/create-pull-request@v4.1.3
        with:
          token: ${{ secrets.PAT }}
          branch: dotbot-submodule-update
          commit-message: Automated update to dotbot submodule
          Title: Automated Update to Dotbot Submodule
